[build]
  command = "pnpm nx build web --prod"
  publish = "dist/apps/web/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "24"
  NX_NO_CLOUD = "true"
  NX_DAEMON = "false"
